# Stages

stages:
  - build
  - lint
  - test

# Configurations

image: node:9.4.0
cache:
  key: "node"
  untracked: true

# Staging

build:
  stage: build
  artifacts:
    paths:
    - dist/
  script:
    - npm install
    - npm run build

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
